let container = document.querySelector("#container");

let codeGeneratedBtn = document.createElement("button");
codeGeneratedBtn.textContent = "Generated by Code";
container.append(codeGeneratedBtn);

container.style.display = "flex";
container.style.justifyContent = "center";
container.style.alignItems = "center";
container.style.height = "100vh";
container.style.flexDirection = "column";
container.style.gap = "100px"

codeGeneratedBtn.addEventListener("click", (e) => {
    alert("Gen by Code")
})

// // constructed event
// let clickEvent = new Event("click", {bubbles: false, cancelable: false});
// codeGeneratedBtn.dispatchEvent(clickEvent);

// let userGeneratedBtn = document.createElement("button");
// userGeneratedBtn.textContent = "Generated by User";
// container.append(userGeneratedBtn);

// userGeneratedBtn.addEventListener("click", (e) => {
//     alert("Gen by User")
// })

// let userGenClickEvent = new Event("click", {bubbles: false, cancelable: false})
// userGeneratedBtn.dispatchEvent(userGenClickEvent);

/********/
// // USE THIS TO QUICKLY ADD A CUSTOM EVENT TO A USER-CREATED BUTTON
// let event = new MouseEvent("click");
// btnRock.dispatchEvent(event);
/*******/

let btnMouseEvent = document.createElement("button");
btnMouseEvent.textContent = "My event is created with MouseEvent";
container.append(btnMouseEvent);

// constructed as a mouse event
let clickMouseEvent = new MouseEvent("click", {bubbles: false, cancelable: false});
// register listener
btnMouseEvent.addEventListener("click", (e) => {
    alert("I was created as a Mouse Event");
})
// dispatch event
btnMouseEvent.dispatchEvent(clickMouseEvent);

let testButton = document.createElement("button");
testButton.textContent = "Click to Test";
container.append(testButton)

// register event listener
testButton.addEventListener("click", (e) => {
    alert("Clicked Test Button")
})
// create custom event
let testEvent = new MouseEvent("click", {bubbles: false, cancelable: false});
// dispatch event
testButton.dispatchEvent(testEvent)


// // constructed as a generic event
// let MouseClickEvent = new Event("click", {bubbles: false, cancelable: false})
// btnMouseEvent.dispatchEvent(MouseClickEvent);